### ISSUE TITLE
Deletes the <script src> tag from the generated html

### ISSUE THREAD

**Issue by pauldmps** [steadyapp/html-webpack-link-type-plugin#4]
Adding this plugin is deleting the <script src=‘bundle.js'> from the body of the generated html. Can you please fix?

**Comment by swimmadude66** [comment]
I am so sorry about that oversight. I changed the way links were detected in the last release, and didn't consider the downstream implications.

I've pushed a fix in PR #5, and am drafting release v1.0.2 right now. It should be available within 5 minutes. I have also added to our unit tests in order to detect problems like this at build time in the future. Sorry again!

**Comment by pauldmps** [comment]
Great! Thanks for the quick fix.
